name: 'Test'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.1.0'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3.5.1'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm clean-install'

      - name: 'Build'
        run: 'npm run build'

      - name: 'Test'
        run: 'npm run test'
